apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docbench

resources:
  - ../../base

patches:
  - path: api-deployment-patch.yaml
    target:
      kind: Deployment
      name: docbench-api
