apiVersion: v1
kind: ConfigMap
metadata:
  name: docbench-config
  namespace: docbench
data:
  AUTO_INIT_DB: "true"
  SQL_ECHO: "false"
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "20"
  DEFAULT_TEMPERATURE: "0.1"
  FLASK_ENV: "production"
  GUNICORN_TIMEOUT: "120"
